## Constants and Variables in Tensorflow

### Constants

In [37]:
# Imports
import tensorflow as tf

# Define a 2x3 constant - that is, 2 rows and 3 columns
a = tf.constant(3, shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [38]:
# Define a 2x2 constant - that is, 2 rows and 2 columns
b = tf.constant([1,2,3,4], shape=[2,2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Variables

In [39]:
# Imports
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
a0

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [52]:
# Define another variable 2x3
a1 = tf.Variable([[5,6,7],[8,9,10]], dtype=tf.float32)
a1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>

In [48]:
# define a constant
c = tf.constant(3, tf.float32)
c

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [51]:
# Compute their product
c0 = tf.multiply(a0, c)
c0

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18.], dtype=float32)>

In [53]:
c1 = tf.multiply(a1, c)
c1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[15., 18., 21.],
       [24., 27., 30.]], dtype=float32)>

### Special Tensors (Ones, Zeros, Ones Like, Zeros Like)

In [31]:
# Imports
import tensorflow as tf

# 0D Tensor
d0 = tf.ones(shape=(1,))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [30]:
# 1D Tensor
d1 = tf.ones(shape=(2,))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [34]:
# 2D Tensor with 4 elements
d2 = tf.ones(shape=(2,2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [35]:
# 2D Tensor with a single element
d2 = tf.ones(shape=(1,1))
d2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [36]:
# 3D Tensor
d3 = tf.ones(shape=(2,2,2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

## Linear Regression with Tensorflow

In [4]:
# Imports
import pandas as pd
import tensorflow as tf
import numpy as np

In [5]:
# Load the data
df = pd.read_csv('kc_house_data.csv')

In [6]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
id               21613 non-null int64
date             21613 non-null object
price            21613 non-null float64
bedrooms         21613 non-null int64
bathrooms        21613 non-null float64
sqft_living      21613 non-null int64
sqft_lot         21613 non-null int64
floors           21613 non-null float64
waterfront       21613 non-null int64
view             21613 non-null int64
condition        21613 non-null int64
grade            21613 non-null int64
sqft_above       21613 non-null int64
sqft_basement    21613 non-null int64
yr_built         21613 non-null int64
yr_renovated     21613 non-null int64
zipcode          21613 non-null int64
lat              21613 non-null float64
long             21613 non-null float64
sqft_living15    21613 non-null int64
sqft_lot15       21613 non-null int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB


In [8]:
# prepare target
target = np.array(df['price'], np.float32)

In [9]:
target.shape

(21613,)

In [10]:
# Extract features
sqft_living = np.array(df['sqft_living'], np.int64)
num_bed = np.array(df['bedrooms'], np.int64)
waterfront = np.array(df['waterfront'], np.int64)

In [30]:
sqft_living.shape, num_bed.shape, waterfront.shape

((21613,), (21613,), (21613,))

### Univariate Linear Regression

In [54]:
# Univariate linear regression model
def uni_reg(intercept, slope, features):
    predictions = intercept+features*slope
    return predictions

In [55]:
# Define loss function - MSE in this case (other loss functions include MAE, Huber)
from tensorflow import keras
def loss_function(intercept, slope, features, targets):
    predictions = uni_reg(intercept, slope, features)
    loss = keras.losses.mse(targets, predictions)
    return loss

In [56]:
# define parameters (intercept and slope)
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [57]:
# Compute loss for the given parameter values
loss = loss_function(intercept, slope, sqft_living, target)

In [58]:
print(loss.numpy())

426199300000.0


In [59]:
# Train a linear model by learning the optimal parameter values
# 1.Initialize optimizer with learning rate of 0.5
opt = keras.optimizers.Adam(0.5)
# 2. Search for the optimal intercept and slope values
for j in range(100):
    opt.minimize(lambda: loss_function(intercept, slope, sqft_living, target), var_list=[intercept, slope])
    # print every 10th value of the loss
    if j%10==0:
        print(loss_function(intercept, slope, sqft_living, target).numpy())
        

424840500000.0
411406070000.0
398277700000.0
385485440000.0
373046500000.0
360967600000.0
349248780000.0
337886400000.0
326875200000.0
316208840000.0


In [60]:
intercept.numpy(), slope.numpy()

(48.370266, 48.39488)

### Multivariate Linear Regression

In [44]:
# Multivariate linear regression
def multi_reg(params, feature1, feature2, feature3):
    return params[0]+feature1*params[1]+feature2*params[2]+feature3*params[3]

In [48]:
# Define parameters
params = tf.Variable([0.1, 0.01, 0.5, 0.25], np.float32)
params

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0.1 , 0.01, 0.5 , 0.25], dtype=float32)>

In [50]:
# Define loss function for multivariate linear regression
from tensorflow import keras
def loss_function_multi(params, feature1, feature2, feature3, targets):
    predictions = multi_reg(params, feature1, feature2, feature3)
    loss = keras.losses.mse(targets, predictions)
    return loss

In [52]:
# Train a linear model by learning the optimal parameter values
# 1.initialize optimizer with learning rate of 0.5
opt = keras.optimizers.Adam(0.5)
# 2. search for the optimal intercept and slope values
for j in range(100):
    opt.minimize(lambda: loss_function_multi(params, sqft_living, num_bed, waterfront, target), var_list=[params])
    # print every 10th value of the loss
    if j%10==0:
        print(loss_function_multi(params, sqft_living, num_bed, waterfront, target).numpy())

425080950000.0
411623000000.0
398472000000.0
385658100000.0
373198500000.0
361100020000.0
349362600000.0
337982720000.0
326954880000.0
316272930000.0


In [53]:
params

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([48.367893, 48.302856, 48.74574 , 49.428825], dtype=float32)>

## Neural Networks with Tensorflow 

### Construct A Simple Dense Layer with A Single Node - Low Level Approach

In [76]:
# Imports
import tensorflow as tf

# Define inputs (features)
inputs = tf.constant([[1, 35]], tf.float32)

# Define weights corresponding to a single node in the dense layer
weights = tf.Variable([[-0.05], [-0.01]])

# Define the bias (similar to intercept in Linear Regression Model)
bias = tf.Variable([0.5])

# Define a dense layer: Multiply input (features) by the weights
product = tf.matmul(inputs, weights)

# Construct dense layer - this corresponds to hidden layer with a single node
dense1 = tf.keras.activations.sigmoid(product+bias)

In [67]:
inputs

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1., 35.]], dtype=float32)>

In [77]:
dense1

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5249792]], dtype=float32)>

### Construct A Dense Layer with Multiple Nodes - Low Level Approach

In [78]:
# Let's do a hidden layer with two nodes
weights = tf.Variable([[-0.05, -0.01], [0.05, 0.01]])

# Define a dense layer
product = tf.matmul(inputs, weights)

# Construct dense layer - a hidden layer with 2 nodes
dense1 = tf.keras.activations.sigmoid(product+bias)

In [79]:
dense1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.9002496, 0.6984652]], dtype=float32)>

In [80]:
# Let's do a hidden layer with three nodes - 2x3 - 2 rows and 3 columns - # rows equal to # features from the previous layer and # columns equals to # nodes in the current hidden layer
weights = tf.Variable([[-0.05, -0.01, 0.05], [0.05, 0.01, 0.06]])

# Define a dense layer
product = tf.matmul(inputs, weights)

# Construct dense layer - multinode
dense1 = tf.keras.activations.sigmoid(product+bias)

In [81]:
dense1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.9002496, 0.6984652, 0.934011 ]], dtype=float32)>

In [73]:
weights.shape

TensorShape([2, 3])

In [82]:
# Construct the 2nd hidden layer with 2 nodes where the nodes from the 1st dense layer is the input
weights = tf.Variable([[0.05, 0.01], [-0.05, -0.01], [0.05, -0.01]])
product2 = tf.matmul(dense1, weights)
dense2 = tf.keras.activations.sigmoid(product2+bias)
dense2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.6357094, 0.620737 ]], dtype=float32)>

In [87]:
# Finally calculate the output layer - the dense 2 is now an input to the output layer
weights = tf.Variable([[0.05], [0.01]])
product3 = tf.matmul(dense2, weights)
output = tf.keras.activations.softmax(product3+bias)
output

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

## 3 Layer Neural Network with Tensorflow - Forward and Back Propagation

In [14]:
# Load the data
import pandas as pd
import numpy as np
df = pd.read_csv('kc_house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [15]:
# Let's select 2 features - take the first 50 examples for simplicity
features = np.array(df.loc[0:50, ['sqft_living', 'bedrooms']], np.float32)
features.shape

(51, 2)

In [16]:
# Prepare input data
inputs = tf.constant(features, np.float32)
inputs.shape

TensorShape([51, 2])

In [17]:
# Actuals
target = np.array(df.loc[0:50, 'price'], np.float32)
actual = tf.constant(target, np.float32, shape=[51, 1])
actual.shape

TensorShape([51, 1])

In [18]:
# Define layer 1 weights: 2 features and 3 nodes
w1 = tf.Variable(tf.random.normal(shape=[2, 3])) 

# Initialize the layer 1 bias: one bias for each node
b1 = tf.Variable(tf.ones([3]))

# Define layer 2 weights: 3 features and 4 nodes
w2 = tf.Variable(tf.random.normal(shape=[3, 4]))

# Initialize the layer 2 bias: one bias for each node
b2 = tf.Variable(tf.ones([4]))

# Define output layer weights: 4 features and 1 node
w_o = tf.Variable(tf.random.normal(shape=[4, 1]))

# Initialize the output layer bias
bo = tf.Variable(0.01)

In [22]:
# Define the architecture of the network and the model
def nn_forward(inputs, w1, w2, w_o, b1, b2, bo):
    layer1_product = tf.matmul(inputs, w1)
    layer1 = tf.keras.activations.relu(layer1_product+b1)
    layer2_product = tf.matmul(layer1, w2)
    layer2 = tf.keras.activations.relu(layer2_product+b2)
    dropout = tf.keras.layers.Dropout(0.25)(layer2)
    output_product = tf.matmul(dropout, w_o)
    output = tf.keras.activations.sigmoid(output_product+bo)
    return output

In [23]:
def nn_loss_function(inputs, w1, w2, w_o, b1, b2, bo, actual):
    prediction = nn_forward(inputs, w1, w2, w_o, b1, b2, bo)
    loss = tf.keras.losses.mse(actual, prediction)
    return loss

In [24]:
# Train the model by learning the optimal weights

opt = tf.keras.optimizers.Adam(0.5) # 1.Initialize optimizer with learning rate of 0.5

for j in range(100): # 2. Search for the optimal values for the weights
    opt.minimize(lambda: nn_loss_function(inputs, w1, w2, w_o, b1, b2, bo, actual), var_list=[w1, w2, w_o, b1, b2, bo]) 

In [28]:
# Make predictions with the model with optimal parameter values
model_predictions = nn_forward(inputs, w1, w2, w_o, b1, b2, bo)

In [31]:
model_predictions.numpy()[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [30]:
# Look at the error for the first 5 examples
actual.numpy()[:5] - model_predictions.numpy()[:5]

array([[221900.],
       [538000.],
       [180000.],
       [604000.],
       [510000.]], dtype=float32)

### Construct A Simple Dense Layer - High Level Approach

In [14]:
# Imports
import tensorflow as tf
from tensorflow import keras

# Define data
data = sqft_living

# Define input (features) layer in 2D (21613 x 1)
inputs = tf.constant([data], tf.float32)

In [54]:
data.shape

(21613,)

In [55]:
data

array([1180, 2570,  770, ..., 1020, 1600, 1020])

In [15]:
inputs

<tf.Tensor: shape=(1, 21613), dtype=float32, numpy=array([[1180., 2570.,  770., ..., 1020., 1600., 1020.]], dtype=float32)>

In [16]:
# Define first dense layer
dense1 = keras.layers.Dense(10, activation='sigmoid')(inputs)

In [17]:
dense1

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 1., 1., 0., 1., 0., 1., 1., 1., 0.]], dtype=float32)>

In [21]:
# Define the second dense layer
dense2 = keras.layers.Dense(5, activation='sigmoid')(dense1)

In [22]:
dense2

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.6996137 , 0.7504355 , 0.69623697, 0.59298015, 0.6162821 ]],
      dtype=float32)>

In [23]:
# Define the output layer
dense3 = keras.layers.Dense(1, activation='sigmoid')(dense2)

In [24]:
dense3

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.46446025]], dtype=float32)>

### Initializing Variables (weights) in Tensorflow

It is very important how you initialize the values of the weights of each layer in the neural network. The initial values of the weights has an impact on finding the global minimum in the loss function. A good initialization can reduce the amount of time needed to find the global minimum

In [5]:
import tensorflow as tf

# Generate random numbers from Normal distribution
tf.random.normal(shape=[5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.8866863 , -1.3876317 ,  0.47401348,  0.15329775,  1.3170416 ],
       [ 0.15854323, -1.5267153 ,  1.0302824 , -1.038911  ,  0.03112386],
       [ 2.101551  ,  1.0562127 , -1.536256  ,  0.8149299 ,  1.2326068 ],
       [-1.1391582 , -1.9199399 ,  0.30888993, -0.75854504,  0.16000947],
       [-0.6484517 ,  0.08019792,  1.6427901 , -0.3066696 ,  0.15376066]],
      dtype=float32)>

In [8]:
# Define 5x5 random normal variables/weights
weights = tf.Variable(tf.random.normal(shape=[5,5]))
weights

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 0.9396075 ,  0.12822331, -0.31845698, -0.18658453,  1.3260667 ],
       [ 0.00658622,  0.27541274, -0.35722962, -1.0681683 , -1.8259572 ],
       [-1.3171089 , -1.1335899 , -0.23154369, -0.55451345, -0.95102245],
       [-0.7896692 , -0.08747762,  0.27104133, -1.2470058 , -0.18533978],
       [-1.4256169 ,  0.02641753, -2.0632882 ,  0.28632152, -0.19306935]],
      dtype=float32)>