## Constants and Variables in Tensorflow

### Constants

In [37]:
# Imports
import tensorflow as tf

# Define a 2x3 constant - that is, 2 rows and 3 columns
a = tf.constant(3, shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [38]:
# Define a 2x2 constant - that is, 2 rows and 2 columns
b = tf.constant([1,2,3,4], shape=[2,2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Variables

In [39]:
# Imports
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
a0

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [52]:
# Define another variable 2x3
a1 = tf.Variable([[5,6,7],[8,9,10]], dtype=tf.float32)
a1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>

In [48]:
# define a constant
c = tf.constant(3, tf.float32)
c

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [51]:
# Compute their product
c0 = tf.multiply(a0, c)
c0

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18.], dtype=float32)>

In [53]:
c1 = tf.multiply(a1, c)
c1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[15., 18., 21.],
       [24., 27., 30.]], dtype=float32)>

### Special Tensors (Ones, Zeros, Ones Like, Zeros Like)

In [31]:
# Imports
import tensorflow as tf

# 0D Tensor
d0 = tf.ones(shape=(1,))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [30]:
# 1D Tensor
d1 = tf.ones(shape=(2,))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [34]:
# 2D Tensor with 4 elements
d2 = tf.ones(shape=(2,2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [35]:
# 2D Tensor with a single element
d2 = tf.ones(shape=(1,1))
d2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [36]:
# 3D Tensor
d3 = tf.ones(shape=(2,2,2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

## Linear Regression with Tensorflow

In [4]:
# Imports
import pandas as pd
import tensorflow as tf
import numpy as np

In [5]:
# Load the data
df = pd.read_csv('kc_house_data.csv')

In [6]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
id               21613 non-null int64
date             21613 non-null object
price            21613 non-null float64
bedrooms         21613 non-null int64
bathrooms        21613 non-null float64
sqft_living      21613 non-null int64
sqft_lot         21613 non-null int64
floors           21613 non-null float64
waterfront       21613 non-null int64
view             21613 non-null int64
condition        21613 non-null int64
grade            21613 non-null int64
sqft_above       21613 non-null int64
sqft_basement    21613 non-null int64
yr_built         21613 non-null int64
yr_renovated     21613 non-null int64
zipcode          21613 non-null int64
lat              21613 non-null float64
long             21613 non-null float64
sqft_living15    21613 non-null int64
sqft_lot15       21613 non-null int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB


In [8]:
# prepare target
target = np.array(df['price'], np.float32)

In [9]:
target.shape

(21613,)

In [10]:
# Extract features
sqft_living = np.array(df['sqft_living'], np.int64)
num_bed = np.array(df['bedrooms'], np.int64)
waterfront = np.array(df['waterfront'], np.int64)

In [30]:
sqft_living.shape, num_bed.shape, waterfront.shape

((21613,), (21613,), (21613,))

### Univariate Linear Regression

In [54]:
# Univariate linear regression model
def uni_reg(intercept, slope, features):
    predictions = intercept+features*slope
    return predictions

In [55]:
# Define loss function - MSE in this case (other loss functions include MAE, Huber)
from tensorflow import keras
def loss_function(intercept, slope, features, targets):
    predictions = uni_reg(intercept, slope, features)
    loss = keras.losses.mse(targets, predictions)
    return loss

In [56]:
# define parameters (intercept and slope)
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [57]:
# Compute loss for the given parameter values
loss = loss_function(intercept, slope, sqft_living, target)

In [58]:
print(loss.numpy())

426199300000.0


In [59]:
# Train a linear model by learning the optimal parameter values
# 1.Initialize optimizer with learning rate of 0.5
opt = keras.optimizers.Adam(0.5)
# 2. Search for the optimal intercept and slope values
for j in range(100):
    opt.minimize(lambda: loss_function(intercept, slope, sqft_living, target), var_list=[intercept, slope])
    # print every 10th value of the loss
    if j%10==0:
        print(loss_function(intercept, slope, sqft_living, target).numpy())
        

424840500000.0
411406070000.0
398277700000.0
385485440000.0
373046500000.0
360967600000.0
349248780000.0
337886400000.0
326875200000.0
316208840000.0


In [60]:
intercept.numpy(), slope.numpy()

(48.370266, 48.39488)

### Multivariate Linear Regression

In [44]:
# Multivariate linear regression
def multi_reg(params, feature1, feature2, feature3):
    return params[0]+feature1*params[1]+feature2*params[2]+feature3*params[3]

In [48]:
# Define parameters
params = tf.Variable([0.1, 0.01, 0.5, 0.25], np.float32)
params

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0.1 , 0.01, 0.5 , 0.25], dtype=float32)>

In [50]:
# Define loss function for multivariate linear regression
from tensorflow import keras
def loss_function_multi(params, feature1, feature2, feature3, targets):
    predictions = multi_reg(params, feature1, feature2, feature3)
    loss = keras.losses.mse(targets, predictions)
    return loss

In [52]:
# Train a linear model by learning the optimal parameter values
# 1.initialize optimizer with learning rate of 0.5
opt = keras.optimizers.Adam(0.5)
# 2. search for the optimal intercept and slope values
for j in range(100):
    opt.minimize(lambda: loss_function_multi(params, sqft_living, num_bed, waterfront, target), var_list=[params])
    # print every 10th value of the loss
    if j%10==0:
        print(loss_function_multi(params, sqft_living, num_bed, waterfront, target).numpy())

425080950000.0
411623000000.0
398472000000.0
385658100000.0
373198500000.0
361100020000.0
349362600000.0
337982720000.0
326954880000.0
316272930000.0


In [53]:
params

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([48.367893, 48.302856, 48.74574 , 49.428825], dtype=float32)>

## Neural Networks with Tensorflow 

### Construct A Simple Dense Layer with A Single Node - Low Level Approach

In [76]:
# Imports
import tensorflow as tf

# Define inputs (features)
inputs = tf.constant([[1, 35]], tf.float32)

# Define weights corresponding to a single node in the dense layer
weights = tf.Variable([[-0.05], [-0.01]])

# Define the bias (similar to intercept in Linear Regression Model)
bias = tf.Variable([0.5])

# Define a dense layer: Multiply input (features) by the weights
product = tf.matmul(inputs, weights)

# Construct dense layer - this corresponds to hidden layer with a single node
dense1 = tf.keras.activations.sigmoid(product+bias)

In [67]:
inputs

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1., 35.]], dtype=float32)>

In [77]:
dense1

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5249792]], dtype=float32)>

### Construct A Dense Layer with Multiple Nodes - Low Level Approach

In [78]:
# Let's do a hidden layer with two nodes
weights = tf.Variable([[-0.05, -0.01], [0.05, 0.01]])

# Define a dense layer
product = tf.matmul(inputs, weights)

# Construct dense layer - a hidden layer with 2 nodes
dense1 = tf.keras.activations.sigmoid(product+bias)

In [79]:
dense1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.9002496, 0.6984652]], dtype=float32)>

In [80]:
# Let's do a hidden layer with three nodes - 2x3 - 2 rows and 3 columns - # rows equal to # features from the previous layer and # columns equals to # nodes in the current hidden layer
weights = tf.Variable([[-0.05, -0.01, 0.05], [0.05, 0.01, 0.06]])

# Define a dense layer
product = tf.matmul(inputs, weights)

# Construct dense layer - multinode
dense1 = tf.keras.activations.sigmoid(product+bias)

In [81]:
dense1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.9002496, 0.6984652, 0.934011 ]], dtype=float32)>

In [73]:
weights.shape

TensorShape([2, 3])

In [82]:
# Construct the 2nd hidden layer with 2 nodes where the nodes from the 1st dense layer is the input
weights = tf.Variable([[0.05, 0.01], [-0.05, -0.01], [0.05, -0.01]])
product2 = tf.matmul(dense1, weights)
dense2 = tf.keras.activations.sigmoid(product2+bias)
dense2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.6357094, 0.620737 ]], dtype=float32)>

In [87]:
# Finally calculate the output layer - the dense 2 is now an input to the output layer
weights = tf.Variable([[0.05], [0.01]])
product3 = tf.matmul(dense2, weights)
output = tf.keras.activations.softmax(product3+bias)
output

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

## 3 Layer Neural Network with Tensorflow - Forward and Back Propagation

In [108]:
def nn_forward(inputs, weights, bias):
    product = tf.matmul(inputs, weights)
    dense = tf.keras.activations.sigmoid(product+bias)
    return dense

In [154]:
def nn_loss_function(inputs, weights, bias, actual):
    prediction = nn_forward(inputs, weights, bias)
    loss = tf.keras.losses.mse(actual, prediction)
    return loss

In [ ]:
def nn_back_prop(inputs, weights, bias, actual, iternations):
    # Train the model by learning the optimal weights
    # 1.Initialize optimizer with learning rate of 0.5
    opt = tf.keras.optimizers.Adam(0.5)
    # 2. Search for the optimal values for the weights
    for j in range(iterations):
        opt.minimize(lambda: nn_back_prop(inputs, weights1, bias, dense1), var_list=[weights1, bias]) # weights for the 1st hidden layer
        opt.minimize(lambda: nn_back_prop(dense1, weights2, bias, dense2), var_list=[weights2, bias]) # weights for the 2nd hidden laye
        opt.minimize(lambda: nn_back_prop(dense2, weights_output, bias, actual), var_list=[weights_output, bias]) # weights for the output layer

In [113]:
# 3 nodes in 1st layer
weights1 = tf.Variable([[-0.05, -0.01, 0.05], [0.05, 0.01, 0.06]])

# 4 nodes in 2nd layer
weights2 = tf.Variable([[-0.05, -0.01, 0.05, 0.1], [0.05, 0.01, 0.06, 0.5], [0.01, 0.02, 0.03, 0.04]])

# Single node in the output layer
weights_output = tf.Variable([[0.05], [0.01], [0.03], [0.02]])

# Define the bias (similar to intercept in Linear Regression Model)
bias = tf.Variable([0.01])

In [105]:
# Load the data
df = pd.read_csv('kc_house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [127]:
# Let's select 2 features
features = np.array(df.loc[0:50, ['sqft_living', 'bedrooms']], np.float32)
features.shape

(51, 2)

In [128]:
# Prepare input data
inputs = tf.constant(features, np.float32)
inputs.shape

TensorShape([51, 2])

In [130]:
# Actuals
target = np.array(df.loc[0:50, 'price'], np.float32)
actual = tf.constant(target, np.float32, shape=[51, 1])
actual.shape

TensorShape([51, 1])

In [133]:
# Calculate values of 1st hidden layer
dense1 = nn_forward(inputs, weights1, bias)
dense1.shape

TensorShape([51, 3])

In [134]:
# Calculate the values of 2nd hidden layer
dense2 = nn_forward(dense1, weights2, bias)
dense2.shape

TensorShape([51, 4])

In [135]:
# Calculate the value of the output layer
output = nn_forward(dense2, weights_output, bias)
output.shape

TensorShape([51, 1])

In [162]:
# Train the model by learning the optimal weights

# 1.Initialize optimizer with learning rate of 0.5
opt = tf.keras.optimizers.Adam(0.5)

# 2. Search for the optimal values for the weights
for j in range(100):
    opt.minimize(lambda: nn_loss_function(inputs, weights1, bias, dense1), var_list=[weights1, bias]) # weights for the 1st hidden layer
    opt.minimize(lambda: nn_loss_function(dense1, weights2, bias, dense2), var_list=[weights2, bias]) # weights for the 2nd hidden layer
    opt.minimize(lambda: nn_loss_function(dense2, weights_output, bias, actual), var_list=[weights_output, bias]) # weights for the output layer

In [163]:
# Print the values of the losses calculated based on the optimal values of weights and bias values
print(nn_loss_function(dense2, weights_output, bias, actual).numpy())

[4.92391670e+10 2.89442922e+11 3.23996406e+10 3.64814795e+11
 2.60098982e+11 1.50062249e+12 6.63057367e+10 8.51758367e+10
 5.26697923e+10 1.04328356e+11 4.38904914e+11 2.19023065e+11
 9.60993772e+10 1.59999197e+11 2.80898929e+11 4.22498697e+11
 1.56024209e+11 2.35224023e+11 3.57206221e+10 5.28995410e+10
 1.48224229e+11 3.99999605e+12 8.12244337e+10 6.38567834e+10
 1.08240339e+11 5.42885356e+10 8.77967114e+11 4.44887663e+11
 1.91843123e+11 5.16959568e+11 3.36979100e+11 7.83994388e+10
 4.72654873e+11 2.86223925e+11 1.04005607e+11 4.84414620e+11
 3.02498906e+11 4.09598722e+11 5.75995208e+10 3.66023803e+11
 3.90623756e+11 6.00623481e+11 7.43025017e+11 4.69223637e+11
 9.54803814e+10 2.38143029e+11 4.43056210e+10 6.16223408e+11
 2.02499097e+11 1.82249731e+12 5.19835443e+10]


In [156]:
weights1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.05     , -3.2393603,  0.05     ],
       [ 0.05     , -3.219319 ,  0.06     ]], dtype=float32)>

In [157]:
weights2

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.05      , -0.01      ,  0.05      ,  0.1       ],
       [-0.37981257, -0.42761916, -0.90708417, -0.47764927],
       [-2.0584655 , -2.0484838 , -2.0346732 , -2.0252624 ]],
      dtype=float32)>

In [158]:
# Learned weights value
weights_output

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[8.066297],
       [8.026297],
       [8.046297],
       [8.036298]], dtype=float32)>

In [159]:
# Learned bias value
bias

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.0767212], dtype=float32)>

### Construct A Simple Dense Layer - High Level Approach

In [14]:
# Imports
import tensorflow as tf
from tensorflow import keras

# Define data
data = sqft_living

# Define input (features) layer in 2D (21613 x 1)
inputs = tf.constant([data], tf.float32)

In [54]:
data.shape

(21613,)

In [55]:
data

array([1180, 2570,  770, ..., 1020, 1600, 1020])

In [15]:
inputs

<tf.Tensor: shape=(1, 21613), dtype=float32, numpy=array([[1180., 2570.,  770., ..., 1020., 1600., 1020.]], dtype=float32)>

In [16]:
# Define first dense layer
dense1 = keras.layers.Dense(10, activation='sigmoid')(inputs)

In [17]:
dense1

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 1., 1., 0., 1., 0., 1., 1., 1., 0.]], dtype=float32)>

In [21]:
# Define the second dense layer
dense2 = keras.layers.Dense(5, activation='sigmoid')(dense1)

In [22]:
dense2

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.6996137 , 0.7504355 , 0.69623697, 0.59298015, 0.6162821 ]],
      dtype=float32)>

In [23]:
# Define the output layer
dense3 = keras.layers.Dense(1, activation='sigmoid')(dense2)

In [24]:
dense3

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.46446025]], dtype=float32)>